services:
  db:
    image: postgres:16
    container_name: pm_pg
    environment:
      POSTGRES_USER: pm_user
      POSTGRES_PASSWORD: pm_pass
      POSTGRES_DB: polymarket
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
